### ISSUE TITLE
Using PiCamera v2 with full 3280x2460 resolution

### ISSUE THREAD

**Issue by vthierry** [cedricve/raspicam#55]
Hi,
  i am using this raspicam.h in the https://gitlab.inria.fr/line/aide-group/aide project, really fine, and experiment bith raspicam::RaspiCam  and raspicam::RaspiCam_cv with a PiCamera v2 which hardware characterisrics are e.g. there https://picamera.readthedocs.io/en/release-1.12/fov.html

 But i only can use a 1280x960 while  3280x2460 resolution is possible, but it fails (see bug log below) it might be some buffer size is not large enough ?

 Please.
Best.

P.S.:  i gonna have side question : what is RaspiCam_Still ? it might be link with my question.

-------------------------------------------------------------------------------------------
Thread 3 "vc.ril.camera" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x6e5feed0 (LWP 7471)]
0x76fba444 in memcpy () from /usr/lib/arm-linux-gnueabihf/libarmmem-v7l.so
--- backtrace ------------------------------------------------------------------------------#0  0x76fba444 in memcpy ()
    at /usr/lib/arm-linux-gnueabihf/libarmmem-v7l.so
#1  0x00000000 in  ()
--- backtrace full -------------------------------------------------------------------------#0  0x76fba444 in memcpy ()
    at /usr/lib/arm-linux-gnueabihf/libarmmem-v7l.so
#1  0x00000000 in  ()

**Comment by birgersp** [comment]
Hi @vthierry, I'm looking for the same information as you.
So far the highest resolution I could use without error is 1920*1920.
Anything more than that and I get the following errors:

> mmal: mmal_vc_port_enable: failed to enable port vc.ril.camera:out:1(BGR3): ENOSPC
> mmal: mmal_port_enable: failed to enable port vc.ril.camera:out:1(BGR3)(0x2022b60) (ENOSPC)
> camera video callback2 erroropen Failed to create camera component/home/pi/repo/raspicam/src/private/private_impl.cpp 103

https://raspberrypi.stackexchange.com/questions/109147/what-resolutions-can-i-use-for-the-raspberry-pi-camera-2-and-how-can-you-tell?noredirect=1#comment186537_109147
